services:
  frpc:
    build: 
      context: .
      args:
        ARCH: amd64
    network_mode: "host"
    restart: always
    volumes:
      - ./config:/frp/config
      - ./log:/frp/log
    entrypoint:
      - '/frp/frpc'
      - '-c'
      - '/frp/frpc.toml'
